### ISSUE TITLE
[코멘트 요청 #2] 컴포넌트 분리와 관련된 질문

### ISSUE THREAD

**Issue by Seol827** [Seol827/assign2#2]
기능과 관련된 질문은 아닙니다..!

마일스톤 과정 중 매니저님께서 보여주신 코드를 보면 input, button 등 요소들을 컴포넌트 파일 자체로 분리하여 사용하고 계신 것 같은데, 전 아직 익숙하지 않아서인지 페이지의 전체적인 부분이 한 번에 파악되지 않는 어려움이 있습니다.

현재는 페이지(path) 기능 별로 나누어 코드를 작성하고 있는데 더 세세한 부분으로 컴포넌트 자체를 분리하여 사용하는 것을 연습해야 할까요?
현업에서 어떤 방법을 더 선호하는지 궁금합니다!

**Comment by nemyung** [comment]
2. 이 방법은 회사에서 정의한 요구사항과 프론트엔드 엔지니어 & 디자이너의 상호 커뮤니케이션에 따라 달라집니다. 거의 취향을 타는 것 같습니다.

- 처음부터 세세하게 쪼개다가 개발 시간을 너무나도 많이 잡아 먹는다면, 분리하지 마시고 작성해보시는걸 권장합니다. 최소 단위 컴포넌트와 같은 부분들은 숙련도가 많이 필요한 내용이고, 정해놨는데 디자인이 급변한다면 그것에 맞춰서 다시 설계하는 시간이 많이 들어요.
- 지금 처럼 기능 별로 나누어 코드를 작성하는 것은 굉장히 바람직해요. 정말 잘하셨어요!


(+참고) 저의 취향은 다음과 같습니다.
- components 폴더에 정의된 컴포넌트들은 비즈니스 로직이 들어가있지 않은 코드로 정의합니다. 이러한 제약사항을 둔 이유는 재사용을 극대화 하기 위함이며 디자이너가 만든 컴포넌트와 일치해야 완전한 뷰를 보여줄 수 있다고 생각하기 때문입니다. 

- 비즈니스 로직과 관련된 컴포넌트는 pages 혹은 domains 라는 폴더 내부에 정의하며, 해당 디렉터리 내부에 비즈니스 로직의 세부 요건별로 서브 디렉토리를 만듭니다. 사전이라고 하면 국어사전, 영어사전 등 사전의 컨텍스트에 따라 서브 디렉토리를 만든다고 생각해주시면 될 것 같네요. 이렇게 나누는 이유는 변화에 빠르게 대처할 수 있도록 미리 배수진을 쳐놓을 수 있기 때문입니다. 국어 사전과 영어 사전의 기본적인 뷰는 같겠지만, 국어 사전에 받아쓰기 기능이 추가되는 경우 빠르게 바꾸기 위함이라고 생각해주시면 좋을 것 같아요.
