### ISSUE TITLE
[코멘트 요청 #3] 삼항연산자 관련 이슈

### ISSUE THREAD

**Issue by Seol827** [Seol827/assign2#3]
입력받을 값의 null을 허용하지 않기 위해 조건문으로 작성을 하였습니다!
<img width="775" alt="image" src="https://user-images.githubusercontent.com/83569413/160546269-0b7c3cbf-f6d9-4e3d-a391-66bc529c9c81.png">

위와 같은 코드에서 if 구문을 삼항연산자로 변경해보니 alert가 활성화되지만 이어서 dispatch와 history까지 모두 실행이 됩니다.
이유가 무엇인지 궁금합니다!

`engWrd.current.value === "" || mean.current.value === "" || example.current.value === ""
? alert('Add your Word, plz')
: dispatch(
            addWordFB({
              eng: engWrd.current.value,
              mean: mean.current.value,
              example: example.current.value,
              time : Date.now(),
            })
          );
          history.push("/");`

삼항연산자 코드는 위와 같습니다.

**Comment by nemyung** [comment]
3. 위에 있는 코드 중 history.push를 제외하고는 다음의 사진처럼 보여지는데요,
![스크린샷 2022-04-03 오후 2 41 15](https://user-images.githubusercontent.com/90446271/161413526-eb188120-ea7a-4801-a809-3e964ab1ec04.png)

- 이경우 alert과 dispatch 둘 중 하나만 실행됩니다. 재현을 해보았으나 두개 다 실행되지는 않고 있네요.

- 그러나 이와 별개로 `history.push("/")`는 그 어느쪽이라도 반드시 실행됩니다. 삼항 연산자는 특정 조건일 때 특정 값을 평가하기 위해 사용됩니다. 따라서 값이 평가되었으니(undefined 또는 Promise가 평가됩니다) 다음 코드가 실행이 되는거지요.

- 삼항 연산자를 쓰는 것이 코드 양을 줄이기 위함이라면 `useRef`를 통해 값을 관리하는 것 보다 폼 자체를 Controlled component으로 만들어서 state가 있는지 없는지의 여부가 좀 더 줄어들 수 있을 것 같네요.

저의 코멘트는 여기까지입니다. 좋은 주말 보내세요!

**Comment by Seol827** [comment]
> 3. 위에 있는 코드 중 history.push를 제외하고는 다음의 사진처럼 보여지는데요,
>    ![스크린샷 2022-04-03 오후 2 41 15](https://user-images.githubusercontent.com/90446271/161413526-eb188120-ea7a-4801-a809-3e964ab1ec04.png)
> 
> * 이경우 alert과 dispatch 둘 중 하나만 실행됩니다. 재현을 해보았으나 두개 다 실행되지는 않고 있네요.
> * 그러나 이와 별개로 `history.push("/")`는 그 어느쪽이라도 반드시 실행됩니다. 삼항 연산자는 특정 조건일 때 특정 값을 평가하기 위해 사용됩니다. 따라서 값이 평가되었으니(undefined 또는 Promise가 평가됩니다) 다음 코드가 실행이 되는거지요.
> * 삼항 연산자를 쓰는 것이 코드 양을 줄이기 위함이라면 `useRef`를 통해 값을 관리하는 것 보다 폼 자체를 Controlled component으로 만들어서 state가 있는지 없는지의 여부가 좀 더 줄어들 수 있을 것 같네요.
> 
> 저의 코멘트는 여기까지입니다. 좋은 주말 보내세요!

**Comment by Seol827** [comment]
@nemyung 3개의 코멘트 모두 세세하게 답변 남겨주셔서 너무 감사드립니다...!!! 말씀해주신대로 리팩토링도 시도해보고, 다시 한번 코드를 보도록하겠습니다!!👍
